### ISSUE TITLE
HTTPS should be mandatory for any kind of authentication, demo or not

### ISSUE THREAD

**Issue by robconery** [Microsoft/TailwindTraders-Website#9]
Currently the Deploy README states:

> Note: Currently https is not supported. Please use http when browsing the web.

I understand this was done for demo purposes, however Azure provides HTTPS for free in its App Services and this is something we should be leveraging - even for a demo.

**Comment by dasanagu** [comment]
Azure App Services is not the issue here, our public endpoints right now don't include SSL, we have this in our backlog and we will re-deploy the backend services with SSL certificate to support HTTPS as soon as possible. Meanwhile if you want to use the website with HTTPS you need to deploy the backend services with SSL and then change the app settings in the website to point to your own backend services.

**Comment by dasanagu** [comment]
Thanks @robconery. On January we will be adding a new public endpoints (backend) with a SSL certificate so we can use HTTPs in the public website without having to deploy the backend services. Assigning @eiximenis to this issue for creating the new environment.

**Comment by robconery** [comment]
Was this closed based on a code fix? I'm looking but can't tell if ssl is required.

**Comment by eiximenis** [comment]
Hi @robconery 

Backend now supports TLS through cert-manager and let's encrypt, so now it is possible to deploy a backend environment with https :)

Additionally is also possible to deploy the web inside the AKS instead of using app service (although this is not related about the https issue).

Instructions about enabling TLS in Backend are in https://github.com/Microsoft/TailwindTraders-Backend/blob/master/Documents/DeploymentGuide.md#enabling-ssltls-on-the-cluster
